[tool.poetry]
name = "tictactoe"
<<<<<<< HEAD
version = "0.1.0"
=======
version = "0.2.0"
>>>>>>> 8d7c195 (build: update release ci step)
description = "A simple tic-tac-toe game in Python"
authors = ["Arkar Min Aung <arica.aung@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.12"
pyinstaller = "^5.9.0"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.9.0"
python-semantic-release = "^7.25.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.1.7"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
<<<<<<< HEAD
    "tictactoe/__init__.py:__version__",
=======
>>>>>>> 8d7c195 (build: update release ci step)
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = false
upload_to_release = true
<<<<<<< HEAD
build_command = "pip install poetry && poetry build"
=======
build_command = "make build"
>>>>>>> 8d7c195 (build: update release ci step)
